config/routes.rb
Rails.application.routes.draw do

  
  root   'posts#index'
  get    '/signup', to:  'users#new'
  post   '/signup', to:  'users#create'
  get    '/login',  to:  'sessions#new'
  post   '/login',  to:  'sessions#create'
  delete '/logout', to:  'sessions#destroy'

  resources :users
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 130 }, allow_nil: false
  validates :body, presence: true, length: { maximum: 2000 }, allow_nil: false

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :posts
  
  validates :name, presence: true, length: { maximum: 50 }, allow_nil: false
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: false
  has_secure_password

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/members_only_controller.rb
class MembersOnlyController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

include SessionsHelper

  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'Your post was successfully created!'
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = 'You must be logged in to do that.'
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = 'You have been logged in.'
      redirect_to root_url
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = "You have been logged out."
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'You signed up successfully'
      redirect_to @user
    else
    render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_only_helper.rb
module MembersOnlyHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    user.remember
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = 'You must be logged in to do that.'
      redirect_to login_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 200 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_site_header.html.erb
<header class="navbar navbar-fixed-top sitewide-nav">
  <div class="container-fluid" >
  <%= link_to "MembersOnly", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if !logged_in? %>
          <li><%= link_to 'Home', root_path %></>
        <% else %>
          <li><%= link_to 'Posts', root_path %></li>
        <% end %>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle profile-dropdown" data-toggle="dropdown"> My Profile <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user, id: "dropdown-link" %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete, id: "dropdown-link" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnlyAuthentication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/site_header'%>
    <div class="container">
      <% flash.each do |type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/members_only/home.html.erb
<div class="center jumbotron home-jumbotron">
  <div>
    <h1>Welcome to MembersOnly</h1>
  </div>
  <div class="home-subtitle">
    <h2 class="text-center">MembersOnly is completely free to join!</h2>
    </hr>
    <h3 class="text-center">Click the button below to sign up</h3>
  </div>
  <%= link_to 'Sign Up', signup_path, class: 'btn btn-primary btn-lg signup-btn' %>

  
</div>

app/views/posts/index.html.erb
<% if !logged_in? %>
  <%= render 'shared/welcome' %>
<% end %>

<h1 class="text-left post-index-page-title">All Posts</h1>
<div class="new-post-button">
  <%= link_to 'Create a new post', new_post_path, class: 'btn btn-primary' %>
</div>
<div class="container">
  <ul>
    <% @posts.each do |post| %>
      <li class="list-unstyled post-index-list row">
        <div class='post-index-container d-flex flex-row'>
          <div class="post-title-time">
            <div class="post-index-title">
              <%= link_to post.title, post_path(post) %>
            </div>
            <div class="post-time">
              Posted <%= distance_of_time_in_words(post.user.created_at, post.created_at)%> ago.
            </div>
          </div>
          <div class="post-index-author">
            <% if logged_in? %>
              by <%= link_to post.user.name, post_path(post) %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<h1>Create a New Post</h1>

<%= form_for(@post) do |f| %>
  <% @post.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </p>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </p>
  <p>
    <%= f.submit 'Create Post', class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<%= link_to 'Back to All Posts', posts_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, 'error') %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_profile.html.erb
<aside class="col-12 profile-container">
  <section class="user_info">
    <div class="gravatar-container w-100 d-flex flex-row justify-content-start">
      <div>
        <%= gravatar_for @user %>
      </div>
      <ul class="list-unstyled">
        <li>
          <h2 class="user-name">
            <%= @user.name %>
          </h2>
        </li>
        <li>
          <h2 class="user-email">  
            <%= @user.email %>
          </h2>
        </li>
      </ul>
    </div>
  </section>
</aside>

app/views/shared/_welcome.html.erb
<div class="center jumbotron home-jumbotron">
  <div>
    <h1>Welcome to MembersOnly</h1>
  </div>
  <div class="home-subtitle">
    <h2 class="text-center">MembersOnly is completely free to join!</h2>
    </hr>
    <h3 class="text-center">Click the button below to sign up</h3>
  </div>
  <%= link_to 'Sign Up', signup_path, class: 'btn btn-primary btn-lg signup-btn' %>
  
</div>

app/views/users/index.html.erb
<h1 class="text-left user-index-page-title">All Users</h1>
  <ul class='container user-index-container'>
    <% @users.each do |user| %>
      <li class="list-unstyled row user-index-list">
        <div class="user-index-profile">
          <div class='gravatar-aside'>
            <%= gravatar_for user, size: 80, class: 'gravatar-aside' %>
          </div>
          <div class="user-index-info d-flex row ">
            <div>
              <%= link_to user.name %>
            </div>
            <div>
              <%= link_to user.email%>
            </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>

app/views/users/new.html.erb
 <h1>Sign Up Form</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user, url: signup_path) do |f| %>
        <%= render 'shared/error_messages' %> 
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit 'Create my account', class: 'btn create-btn signup-btn btn-primary' %>

      <% end %>
    </div>
  </div>

app/views/users/show.html.erb
<h1>User Profile</h1>
<div class="row">
  <%= render 'shared/user_profile'%>
</div